#ifndef MODE_HANDLER_H
#define MODE_HANDLER_H

#include <Arduino.h>                                             // Include Arduino library for ESP32
#include <esp_log.h>

#include "bluetooth_handler.h"       
#include "waveform_handler.h"         // Include waveform handler for waveform generation                                      

// declarations

/* Operating modes
 * This enum defines the operating modes for the device.
 * The device can operate in either Bluetooth mode or Waveform mode.
 */
typedef enum {
    MODE_BLUETOOTH,
    MODE_WAVEFORM
} operating_mode_t;

//public

/* Setup operating mode function
 * This function will set the operating mode for the device.
 @param operating_mode_t enum
 */
void set_operating_mode(operating_mode_t mode);                             

/* Get operating mode function
 * This function will return the current operating mode of the device.
 * It will return an operating_mode_t enum.
 */
operating_mode_t get_operating_mode(void);                     

/* Toggle operating mode function
 * This function will toggle the operating mode of the device.
 * It will switch between Bluetooth mode and Waveform mode.
 */
void toggle_operating_mode();                                

/* Cycle waveforms function
 * This function will cycle through the available waveforms.
 * It will change the waveform being generated by the device.
 * It is called on short press of the button.
 */
void cycle_waveforms();                                 // Cycle through waveforms

#endif // MODE_HANDLER_H